"use client";

import { useState } from "react";
import { useLoginMutation, useGetMeQuery } from "../_features/authApi";
import { logout } from "../_features/authSessionSlice";
import { useAppDispatch, useAppSelector } from "../_store/hooks";

const DEMO = { email: "demo@notes.local", password: "password123" };

export default function RtkQueryDemo() {
  const dispatch = useAppDispatch();
  const token = useAppSelector((s) => s.authSession.token);
  const user = useAppSelector((s) => s.authSession.user);
  const [email, setEmail] = useState(DEMO.email);
  const [password, setPassword] = useState(DEMO.password);

  const [login, loginState] = useLoginMutation();
  const meQuery = useGetMeQuery(undefined, { skip: !token });

  return (
    <div className="max-w-md space-y-4 text-sm">
      {!token ? (
        <form
          className="space-y-2"
          onSubmit={async (e) => {
            e.preventDefault();
            await login({ email, password });
          }}
        >
          <p className="text-xs text-zinc-500">
            Same mock API as Example 4 — hooks generated by RTK Query.
          </p>
          <input
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            className="w-full rounded border border-zinc-300 px-2 py-1 dark:border-zinc-600 dark:bg-zinc-950"
          />
          <input
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            className="w-full rounded border border-zinc-300 px-2 py-1 dark:border-zinc-600 dark:bg-zinc-950"
          />
          <button
            type="submit"
            disabled={loginState.isLoading}
            className="rounded bg-blue-600 px-3 py-1.5 text-white disabled:opacity-50"
          >
            {loginState.isLoading ? "Logging in…" : "Login (mutation)"}
          </button>
          {loginState.error ? (
            <p className="text-red-600">Login failed — check credentials</p>
          ) : null}
        </form>
      ) : (
        <div className="space-y-2">
          <p>
            Session user: <strong>{user?.name ?? "—"}</strong>
          </p>
          <p className="text-zinc-600 dark:text-zinc-400">
            getMe query:{" "}
            {meQuery.isLoading
              ? "loading…"
              : meQuery.isError
                ? "error (token invalid)"
                : meQuery.data?.email}
          </p>
          <button
            type="button"
            className="rounded border border-zinc-300 px-3 py-1 dark:border-zinc-600"
            onClick={() => dispatch(logout())}
          >
            Logout (clear session slice)
          </button>
        </div>
      )}
      <p className="text-xs text-zinc-500">
        RTK Query owns request lifecycle, cache, and hooks. Use thunks when you need custom imperative
        flows; use RTK Query for server data sync.
      </p>
    </div>
  );
}
