import type { TopicMeta } from "./types";

export const NOTE_TOPICS: TopicMeta[] = [
  {
    id: "html",
    category: "core",
    file: "01-html.md",
    title: "HTML",
    pill: "Structure & semantics",
    description: "HTML5, semantic elements, forms, accessibility, SEO, and performance.",
    navNext: { href: "/notes/css", label: "CSS notes" },
  },
  {
    id: "css",
    category: "core",
    file: "02-css.md",
    title: "CSS",
    pill: "Layout & styling",
    description: "Selectors, cascade, Flexbox, Grid, responsive design, and animations.",
    navNext: { href: "/notes/javascript", label: "JavaScript notes" },
  },
  {
    id: "javascript",
    category: "core",
    file: "03-javascript.md",
    title: "JavaScript",
    pill: "Core language",
    description: "From types and closures to async, DOM, and machine-coding classics.",
    navNext: { href: "/notes/typescript", label: "TypeScript notes" },
    extraLinks: [
      { href: "/notes/javascript/concepts", label: "JS Concepts →" },
      { href: "/notes/javascript/methods", label: "JS Methods →" },
    ],
  },
  {
    id: "typescript",
    category: "core",
    file: "09-typescript.md",
    title: "TypeScript",
    pill: "Static typing",
    description: "Types, interfaces, generics, utility types, React and Next.js patterns.",
    navNext: { href: "/notes/react", label: "React notes" },
    extraLinks: [{ href: "/notes/javascript/concepts/typescript-types", label: "Types cheatsheet →" }],
  },
  {
    id: "react",
    category: "core",
    file: "04-reactjs.md",
    title: "React",
    pill: "UI library",
    description: "Hooks, rendering, performance, routing, patterns, and TypeScript.",
    navNext: { href: "/notes/nextjs", label: "Next.js notes" },
  },
  {
    id: "nextjs",
    category: "core",
    file: "05-nextjs.md",
    title: "Next.js",
    pill: "Full-stack React",
    description: "App Router, RSC, SSR/SSG/ISR, Server Actions, auth, and deployment.",
    navNext: { href: "/notes/redux", label: "Redux notes" },
    extraLinks: [{ href: "/learn", label: "Live rendering demos →" }],
  },
  {
    id: "redux",
    category: "core",
    file: "06-redux-redux-toolkit.md",
    title: "Redux & RTK",
    pill: "State management",
    description: "Redux data flow, Redux Toolkit, async thunks, and RTK Query basics.",
    navNext: { href: "/notes/react-query", label: "React Query notes" },
    extraLinks: [{ href: "/learn/redux", label: "Redux playground →" }],
  },
  {
    id: "react-query",
    category: "core",
    file: "07-react-query.md",
    title: "React Query",
    pill: "Server state",
    description: "TanStack Query caching, mutations, invalidation, and testing.",
    navNext: { href: "/notes/jest", label: "Jest notes" },
  },
  {
    id: "jest",
    category: "core",
    file: "08-jest-testing.md",
    title: "Jest & Testing",
    pill: "Testing",
    description: "Jest, React Testing Library, MSW, mocks, and interview scenarios.",
    navNext: { href: "/notes/git", label: "Git notes" },
  },
  {
    id: "git",
    category: "core",
    file: "12-git.md",
    title: "Git",
    pill: "Version control",
    description: "Mental model, rebase, cherry-pick, stash, reset, conflicts, and Cursor Git UI.",
    navNext: { href: "/notes/html", label: "HTML notes" },
  },
  {
    id: "infosys",
    category: "company",
    file: "10-infosys-prep.md",
    title: "Infosys Prep",
    pill: "Company prep",
    description: "ReactJS Developer · Pune · Sep 5 2026 · Sawata Gore",
    hubBadge: "Infosys",
    navNext: { href: "/notes/bajaj", label: "Bajaj prep" },
    extraLinks: [{ href: "/notes/git", label: "Git notes →" }],
  },
  {
    id: "bajaj",
    category: "company",
    file: "11-bajaj-prep.md",
    title: "Bajaj Finserv Prep",
    pill: "Company prep",
    description: "Next.js Developer · 3–6 YOE · Full-stack frontend",
    hubBadge: "Bajaj Finserv",
    navNext: { href: "/notes/infosys", label: "Infosys prep" },
  },
];

export const STUDY_PLAN = [
  { week: "1", topics: "HTML + CSS", focus: "Semantics, layout, responsive" },
  { week: "2", topics: "JavaScript (part 1)", focus: "Types, functions, scope, closures" },
  { week: "3", topics: "JavaScript (part 2) + TypeScript", focus: "Async, DOM, types & generics" },
  { week: "4", topics: "React", focus: "Hooks, Fiber, performance, React 19" },
  { week: "5", topics: "Next.js", focus: "App Router, RSC, auth, deployment" },
  { week: "6", topics: "Redux + React Query", focus: "Client vs server state" },
  { week: "7", topics: "Jest + RTL", focus: "MSW, Next.js testing" },
  { week: "8", topics: "Infosys prep", focus: "Live coding, Redux, behavioral" },
  { week: "9", topics: "Bajaj prep", focus: "Next.js scenarios, system design" },
  { week: "10", topics: "Full revision", focus: "Must-know across all topics" },
] as const;

export function getTopic(id: string): TopicMeta | undefined {
  return NOTE_TOPICS.find((topic) => topic.id === id);
}
